#!/usr/bin/env python3
"""Assemble QUANTITATIVE_RESULTS.md for the paper from computed artifacts."""

from __future__ import annotations

import csv
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from lunar_elf.constants import C0, R_MOON  # noqa: E402
from lunar_elf.sphere.impedance import ideal_schumann_freq  # noqa: E402

OUT = ROOT / "paper" / "QUANTITATIVE_RESULTS.md"
PHASE0 = ROOT / "results" / "phase0" / "shell_metrics.csv"
PHASE1 = ROOT / "results" / "phase1" / "q_table.csv"


def _read_csv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open() as fh:
        return list(csv.DictReader(fh))


def _fmt(v, fmt=".3g"):
    try:
        x = float(v)
        if not np.isfinite(x):
            return "—"
        return format(x, fmt)
    except (TypeError, ValueError):
        return "—"


def main() -> None:
    p0 = _read_csv(PHASE0)
    p1 = _read_csv(PHASE1)
    f1 = ideal_schumann_freq(1, R_MOON)

    L: list[str] = []
    L.append("# Quantitative ELF Results — Lunar Outer Shell\n\n")
    L.append("Generated by `lunar-elf` v0.1.0\n\n")
    L.append(f"- Moon radius R = {R_MOON/1e3:.1f} km\n")
    L.append(f"- c = {C0:.6e} m/s\n")
    L.append(f"- Ideal closed-cavity Schumann f₁ = (c/2πR)√2 = **{f1:.2f} Hz**\n\n")

    L.append("## Method summary\n\n")
    L.append(
        "1. **Phase 0** — outer-shell (0–300 km) log-mean σ_eff; skin depth "
        "δ=√(2/ωμσ); loss tangent tanδ=σ/(ωε); circumferential path attenuation; "
        "shell-path Q upper bound Q ≲ β/(2α) with β=ω√(με).\n"
    )
    L.append(
        "2. **Phase 1** — planar layered surface-impedance recursion looking into "
        "σ(r); Model **A** open Moon (no ionosphere ⇒ no cavity); Model **B** "
        "artificial ionosphere at 100 km with "
        "Q ≈ ωμ₀h / [2 Re(Z_g+Z_i)]; Model **C** Earth validation.\n"
    )
    L.append(
        "3. Profiles are literature-bracketed synthetics "
        "(optimistic / nominal / Apollo-style / pessimistic).\n\n"
    )

    L.append("## Phase 0 — Outer-shell metrics\n\n")
    L.append(
        "| Profile | f (Hz) | σ_eff (S/m) | δ (km) | tanδ | Regime | "
        "A_½circ (dB) | Q_path ≲ |\n"
    )
    L.append("|---|---:|---:|---:|---:|---|---:|---:|\n")
    for r in p0:
        if float(r["f_hz"]) not in (1.0, 10.0, 30.0):
            continue
        L.append(
            f"| {r['profile']} | {float(r['f_hz']):g} | {float(r['sigma_eff']):.2e} | "
            f"{float(r['skin_depth_km']):.1f} | {float(r['loss_tangent']):.2e} | "
            f"{r['regime']} | {float(r['att_half_circ_db']):.1f} | "
            f"{float(r['Q_path_upper']):.3g} |\n"
        )

    L.append("\n### Terminology note (for paper §3)\n\n")
    L.append(
        "Across the nominal and Apollo-style envelopes at 1–30 Hz, **tanδ ≫ 1**: "
        "conduction current dominates. The outer shell is a **weakly conducting "
        "medium with large skin depth**, not a low-loss dielectric (which would "
        "require tanδ ≪ 1). Absolute attenuation lengths can still be hundreds of "
        "km because σ is small — but a lunar circumference is many skin depths for "
        "nominal profiles, so global shell-guided waves are heavily attenuated.\n"
    )

    L.append("\n## Phase 1 — Global-mode Q\n\n")
    L.append("### Model A — Open Moon (physical case)\n\n")
    L.append(
        "No conducting ionosphere ⇒ **no Earth-like closed Schumann cavity** "
        "(cavity Q ≡ 0 in the impedance formula). Shell-path upper bounds for any "
        "would-be circumferential standing wave in the outer shell:\n\n"
    )
    L.append("| Profile | f (Hz) | δ (km) | Q_cavity | Q_path ≲ | Round-trip att (dB) |\n")
    L.append("|---|---:|---:|---:|---:|---:|\n")
    for r in p1:
        if r["model"] != "A_open":
            continue
        L.append(
            f"| {r['profile']} | {float(r['f_hz']):g} | {_fmt(r.get('skin_depth_km'), '.1f')} | "
            f"0 | {_fmt(r.get('Q_path_upper'))} | {_fmt(r.get('round_trip_att_db'), '.1f')} |\n"
        )

    L.append("\n### Model B — Hypothetical closed cavity (Moon + 100 km ionosphere)\n\n")
    L.append(
        "Even granting an artificial upper wall, finite σ(r) damps global modes via "
        "ground surface resistance Re(Z_g). Primary metric: "
        "**impedance-method cavity Q**.\n\n"
    )
    L.append(
        "| Profile | n | f (Hz) | Re(Z_g) (Ω) | Re(Z_i) (Ω) | Q_cavity | Q_path ≲ |\n"
    )
    L.append("|---|---:|---:|---:|---:|---:|---:|\n")
    for r in p1:
        if r["model"] != "B_closed":
            continue
        L.append(
            f"| {r['profile']} | {int(float(r['n']))} | {float(r['f_hz']):.2f} | "
            f"{_fmt(r.get('Re_Zg'), '.3e')} | {_fmt(r.get('Re_Zi'), '.3e')} | "
            f"{_fmt(r.get('Q'))} | {_fmt(r.get('Q_path_upper'))} |\n"
        )

    L.append("\n### Model C — Earth validation\n\n")
    L.append("| n | f_ideal (Hz) | Re(Z_g) (Ω) | Q_cavity |\n")
    L.append("|---:|---:|---:|---:|\n")
    for r in p1:
        if r["model"] != "C_earth":
            continue
        L.append(
            f"| {int(float(r['n']))} | {float(r['f_hz']):.2f} | "
            f"{_fmt(r.get('Re_Zg'), '.3e')} | {_fmt(r.get('Q'))} |\n"
        )
    L.append(
        "\nEarth ideal f₁ ≈ 10.6 Hz (PEC formula); observed Earth Schumann is ~7.8 Hz "
        "with ionosphere corrections. Expected cavity Q of order **few–tens** for a "
        "reasonable ground+ionosphere stack — use as smoke test, not a precision "
        "Earth model.\n"
    )

    L.append("\n## Ringing times (Model B, n=1)\n\n")
    L.append("τ_ring ≈ Q / (π f). Short τ ⇒ no sustained global ring.\n\n")
    L.append("| Profile | Q | f₁ (Hz) | τ_ring (s) |\n")
    L.append("|---|---:|---:|---:|\n")
    for r in p1:
        if r["model"] != "B_closed" or int(float(r["n"])) != 1:
            continue
        try:
            q = float(r["Q"])
            f = float(r["f_hz"])
            tau = q / (np.pi * f)
            L.append(f"| {r['profile']} | {q:.3g} | {f:.2f} | {tau:.3f} |\n")
        except ValueError:
            pass

    L.append("\n## Paper-ready claims\n\n")
    L.append(
        "1. At 1–30 Hz, literature-bracketed outer-shell conductivities give "
        "**tanδ ≫ 1** (conduction-dominated): a **weak conductor with large skin "
        "depth**, not a low-loss dielectric.\n"
    )
    L.append(
        "2. Without an ionosphere (**Model A**), there is **no closed global cavity**.\n"
    )
    L.append(
        "3. Even with a **hypothetical** 100 km ionosphere (**Model B**), cavity Q "
        "is set by Re(Z_g)+Re(Z_i) and remains modest for conductive profiles; "
        "continuous σ(r) provides distributed wall loss.\n"
    )
    L.append(
        "4. Circumferential shell paths span many skin depths for nominal σ "
        "(half-circumference attenuations of tens to hundreds of dB), so "
        "shell-guided global standing waves are not supported.\n"
    )
    L.append(
        "5. Scope is **1-D radial stratification** (layered impedance + path "
        "integrals). Lateral heterogeneity is future work.\n"
    )

    L.append("\n## Figures\n\n")
    for name in [
        "fig_sigma_profiles.png",
        "fig_skin_depth.png",
        "fig_loss_tangent.png",
        "fig_path_attenuation.png",
        "fig_skin_vs_depth.png",
        "fig_Q_summary.png",
        "fig_Q_vs_freq.png",
        "fig_surface_impedance.png",
        "fig_transfer_90deg.png",
        "fig_transfer_vs_angle.png",
        "fig_driven_multipoles.png",
    ]:
        L.append(f"- `paper_figs/{name}`\n")

    L.append("\n## Reproducibility\n\n```bash\n")
    L.append("cd /home/nick/Projects/lunar-elf\n")
    L.append("python scripts/00_build_profiles.py\n")
    L.append("python scripts/01_skin_maps.py\n")
    L.append("python scripts/02_cavity_q_sweep.py\n")
    L.append("python scripts/03_driven_transfer.py\n")
    L.append("python scripts/04_make_paper_figs.py\n")
    L.append("```\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(L))
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
